indent-width = 4
line-length = 88
target-version = "py39"

[lint]
ignore = [
  "ARG001",  # unused-function-argument
  "ARG002",  # unused-method-argument
  "ASYNC109",  # async-function-with-timeout
  "B006",  # mutable-argument-default
  "B008",  # function-call-in-default-argument
  "B017",  # assert-raises-exception
  "COM812",  # missing-trailing-comma
  "COM819",  # prohibited-trailing-comma
  "D206",  # indent-with-spaces
  "D300",  # triple-single-quotes
  "E111",  # indentation-with-invalid-multiple
  "E114",  # indentation-with-invalid-multiple-comment
  "E117",  # over-indented
  "E501",  # line-too-long
  "E731",  # lambda-assignment
  "E741",  # ambiguous-variable-name
  "ISC001",  # single-line-implicit-string-concatenation
  "ISC002",  # multi-line-implicit-string-concatenation
  "LOG015",  # root-logger-call
  "N803",  # invalid-argument-name
  "N806",  # non-lowercase-variable-in-function
  "PLC0415",  # import-outside-top-level
  "PLR09",  # too-many-*
  "PLR1702",  # too-many-nested-blocks
  "PLR1704",  # redefined-argument-from-local
  "PLR2",
  "PLR6301",  # no-self-use
  "PLW0603",  # global-statement
  "PLW1514",  # unspecified-encoding
  "PLW2901",  # redefined-loop-name
  "PT001",  # pytest-fixture-incorrect-parentheses-style
  "PT006",  # pytest-parametrize-names-wrong-type
  "PT011",  # pytest-raises-too-broad
  "PT018",  # pytest-composite-assertion
  "PT023",  # pytest-incorrect-mark-parentheses-style
  "PYI015",  # assignment-default-in-stub
  "PYI021",  # docstring-in-stub
  "PYI025",  # unaliased-collections-abc-set-import
  "PYI041",  # redundant-numeric-union
  "UP046",  # non-pep695-generic-class
  "UP047",  # non-pep695-generic-function
  "Q000",  # bad-quotes-inline-string
  "Q001",  # bad-quotes-multiline-string
  "Q002",  # bad-quotes-docstring
  "Q003",  # avoidable-escaped-quote
  "S101",  # assert
  "S105",  # hardcoded-password-string
  "S110",  # try-except-pass
  "S311",  # suspicious-non-cryptographic-random-usage
  "S404",  # suspicious-subprocess-import
  "S6",
  "SIM105",  # suppressible-exception
  "SIM108",  # if-else-block-instead-of-if-exp
  "SLF001",  # private-member-access
  "TRY003",  # raise-vanilla-args
  "W191",  # tab-indentation
]
select = [
  "ARG",  # flake8-unused-arguments
  "ASYNC",  # flake8-async
  "B",  # flake8-bugbear
  "C4",  # flake8-comprehensions
  "D200",  # unnecessary-multiline-docstring
  "D201",  # blank-line-before-function
  "D202",  # blank-line-after-function
  "D207",  # under-indentation
  "D208",  # over-indentation
  "D209",  # new-line-after-last-paragraph
  "D210",  # surrounding-whitespace
  "D211",  # blank-line-before-class
  "D403",  # first-word-uncapitalized
  "D418",  # overload-with-docstring
  "D419",  # empty-docstring
  "DTZ",  # flake8-datetimez
  "E4",  # pycodestyle
  "E7",
  "E9",
  "F",  # pyflakes
  "FAST",  # fastapi
  "FLY",  # flynt
  "FURB",  # refurb
  "G",  # flake8-logging-format
  "I",  # isort
  "ICN",  # flake8-import-conventions
  "INT",  # flake8-gettext
  "ISC",  # flake8-implicit-str-concat
  "LOG",  # flake8-logging
  "N",  # pep8-naming
  "NPY",  # numpy
  "PERF",  # perflint
  "PIE",  # flake8-pie
  "PLC",  # pylint
  "PLE",  # pylint
  "PLR",  # pylint
  "PLW",  # pylint
  "PT",  # flake8-pytest-style
  "PYI",  # flake8-pyi
  "Q",  # flake8-quotes
  "RSE",  # flake8-raise
  "RUF",  # ruff
  "S",  # flake8-bandit
  "SIM",  # flake8-simplify
  "SLF",  # flake8-self
  "SLOT",  # flake8-slots
  "T10",  # flake8-debugger
  "TD006",  # invalid-todo-capitalization
  "TC",  # flake8-type-checking
  "TID",  # flake8-tidy-imports
  "TRY",  # tryceratops
  "UP",  # pyupgrade
  "W6",
  "YTT",  # flake8-2020
]
extend-safe-fixes = ["D2"]
fixable = ["ALL"]
unfixable = []

[lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"
multiline-quotes = "double"

[lint.pylint]
max-args = 10

[format]
quote-style = "single"
preview = true
