[package]
name = "osm_shortlink"
version = "1.4.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]
name = "osm_shortlink"

[dependencies]
pyo3 = { version = "0.27.2", features = ["extension-module"] }

[profile.release]
overflow-checks = true
lto = true
codegen-units = 1
