[package]
name = "zid"
version = "1.5.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]
name = "zid"

[dependencies]
pyo3 = { version = "0.27.2", features = ["extension-module"] }
rand = "0.9.2"

[profile.release]
lto = true
codegen-units = 1
